### PR TITLE
Update ARI

### PR DESCRIPTION
**Pull request by carsenk**
Updated ARI information and included IPFS hosted logo

### CODE REVIEW

**Comment by dharmabrendan** [comment]
Thanks for your submission @carsenk ! 

Couple comments:

1. Please remove the edits to tokenlist.json — this file auto-updates and does not accept manual updates.
2. We recommend making the description more concise and informative about what exactly ARI does. Right now you provide the supply cap, but users would still have no idea what it is that ARI is used for. You can remove this phrase as well, as all tokens in Dharma are ERC20s on Ethereum: "is an ERC20 token powered by the Ethereum blockchain."

**Comment by carsenk** [comment]
Fixed.

**Review by dharmabrendan — APPROVED** [review]

**Comment by dharmabrendan** [comment]
Thanks for making those updates @carsenk! This has been merged 🙏

**Comment by carsenk** [comment]
> Thanks for making those updates @carsenk! This has been merged 🙏

Does the metadata.json have an option for the logoURI as well? Also wondering why it is showing Unverified in app still? Does it take sometime for it to propagate? Thanks!

**Pull request merged**
